name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: swift build -v

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: swift test -v
