name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode version
        run: sudo xcode-select -s "/Applications/Xcode_15.0.1.app/Contents/Developer"
      - name: build
        run: swift build -v

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: swift test -v
